name: docker-ros2-camera-jazzy
services:
  ros2_camera:
    build:
      context: .
      dockerfile: ./Dockerfile-jazzy-realsense
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    user: ros
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      - ROS_DOMAIN_ID=5
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_LOCALHOST_ONLY=0
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../src:/home/ros/ros2_ws/src
      - /dev:/dev
    device_cgroup_rules:
      - 'c 81:* rmw'
      - 'c 189:* rmw'
    command:
      - bash
      - -c
      - |
        source "/opt/ros/jazzy/setup.bash"
        ros2 launch realsense2_camera rs_launch.py \
          align_depth.enable:=true \
          pointcloud.enable:=false \
          depth_module.profile:=640x480x15 \
          rgb_camera.profile:=640x480x15 \
          enable_infra1:=false \
          enable_infra2:=false
 