FROM ros:jazzy-perception

ENV WS_DIR="/ros2_ws"
WORKDIR ${WS_DIR}

SHELL ["/bin/bash", "-c"]

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
   && apt-get install -y \
   build-essential \
   cmake \
   git-all \
   software-properties-common \
   && rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG USERNAME=ros
ARG USER_ID=1000
ARG GROUP_ID=$USER_ID

RUN set -eux; \
   if ! getent group "${GROUP_ID}" >/dev/null; then \
      groupadd --gid "${GROUP_ID}" "${USERNAME}"; \
   fi; \
   if id -u "${USERNAME}" >/dev/null 2>&1; then \
      usermod --uid "${USER_ID}" --gid "${GROUP_ID}" "${USERNAME}"; \
   elif getent passwd "${USER_ID}" >/dev/null; then \
      EXISTING_USER="$(getent passwd "${USER_ID}" | cut -d: -f1)"; \
      usermod --login "${USERNAME}" --home "/home/${USERNAME}" --move-home "${EXISTING_USER}"; \
      usermod --gid "${GROUP_ID}" "${USERNAME}"; \
   else \
      useradd -s /bin/bash --uid "${USER_ID}" --gid "${GROUP_ID}" -m "${USERNAME}"; \
   fi; \
   mkdir -p "/home/${USERNAME}/.config"; \
   chown -R "${USER_ID}:${GROUP_ID}" "/home/${USERNAME}"

# Ensure ros user can access ROS setup.bash by giving proper permissions
RUN chmod +rx /opt/ros/jazzy/setup.bash

COPY ../entrypoint.sh /entrypoint.sh
COPY ../bashrc /home/$USERNAME/.bashrc

RUN apt-get update \
   && apt-get install -y \
   ros-${ROS_DISTRO}-librealsense2* \
   ros-${ROS_DISTRO}-realsense2-* \
   && rm -rf /var/lib/apt/lists/*

RUN apt-get update \
   && apt-get install -y \
   ros-${ROS_DISTRO}-rviz2 \
   && rm -rf /var/lib/apt/lists/*

ARG DEBIAN_FRONTEND=dialog
 