FROM osrf/ros:jazzy-desktop-full

RUN apt-get update \
    && apt-get install -y \
    nano \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG USERNAME=ros
ARG USER_ID=1001
ARG GROUP_ID=$USER_ID

RUN groupadd --gid $GROUP_ID $USERNAME \
    && useradd -s /bin/bash --uid $USER_ID --gid $GROUP_ID -m $USERNAME \
    && mkdir /home/$USERNAME/.config && chown $USER_ID:$GROUP_ID /home/$USERNAME/.config

# Ensure ros user can access ROS setup.bash by giving proper permissions
# RUN sudo chmod +rx /opt/ros/jazzy/setup.bash
RUN chmod +rx /opt/ros/jazzy/setup.bash


RUN apt-get update \
    && apt-get install -y lsb-release wget gnupg \
    && rm -rf /var/lib/apt/lists/*


# Choose from fortress, garden, and harmonic.
ARG GZ_VERSION=harmonic
ENV GZ_VERSION=${GZ_VERSION}
# Install Gazeob Harmonic
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null \
    && apt-get update \
    && apt-get install -y "gz-${GZ_VERSION}"  \
    && rm -rf /var/lib/apt/lists/*


# Install the matching ros_gz version, eg. `ros-jazzy-ros-gz`.
RUN apt-get update \
    && apt-get install -y "ros-${ROS_DISTRO}-ros-gz" emacs python3-rosdep htop byobu python3 pip less ros-${ROS_DISTRO}-teleop-twist-keyboard ros-${ROS_DISTRO}-desktop \
    && rm -rf /var/lib/apt/lists/*

# For colcon to build python packages without errors we'll need
# RUN pip install --break-system-packages "setuptools<66"


# Build turtlebot4 and ros_gz from source
WORKDIR /home/$USERNAME

RUN mkdir -p ~/ros2_ws/src
RUN mkdir -p ~/turtlebot_ws/src

WORKDIR /home/$USERNAME/turtlebot_ws/src
RUN git clone https://github.com/turtlebot/turtlebot4_simulator -b ${ROS_DISTRO}


RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    apt-get update

# build turtlebot4 packages in turtlebot_ws
WORKDIR /home/$USERNAME/turtlebot_ws
RUN rosdep update
RUN rosdep install -y \
    --from-paths src \
    --ignore-src \
    && rm -rf /var/lib/apt/lists/*



RUN . /opt/ros/$ROS_DISTRO/setup.sh && \
    colcon build --symlink-install

WORKDIR /home/$USERNAME/ros2_ws


# USER $USERNAME
COPY entrypoint.sh /entrypoint.sh
COPY bashrc /home/$USERNAME/.bashrc

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]

CMD ["bash"]

USER root
