 # Note: Run `xhost +local:docker` on the host before starting this container
name: docker-ros2-gui-humble
services:
  ros2_gui_humble:
    #image: osrf/ros:humble-desktop
    build:
      context: .
      dockerfile: ./Dockerfile-humble-gui
    stdin_open: true
    tty: true
    network_mode: host
    ipc: host
    user: ros
    environment:
      - DISPLAY=$DISPLAY
      - QT_X11_NO_MITSHM=1
      # - NVIDIA_DRIVER_CAPABILITIES=all
      # - NVIDIA_VISIBLE_DEVICES=all
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ../src:/home/ros/ros2_ws/src
    command: "bash -c 'source /opt/ros/humble/setup.bash && exec $SHELL'"
