FROM osrf/ros:jazzy-desktop-full

RUN apt-get update \
  && apt-get install -y \
  nano \
  vim \
  && rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG USERNAME=ros
ARG USER_ID=1001
ARG GROUP_ID=$USER_ID

# Add video group (use GID from host)
# RUN groupadd --gid 44 video

# Create user with video group as supplementary
RUN groupadd --gid $GROUP_ID $USERNAME \
  && useradd -s /bin/bash --uid $USER_ID --gid $GROUP_ID -m -G video $USERNAME \
  && mkdir /home/$USERNAME/.config && chown $USER_ID:$GROUP_ID /home/$USERNAME/.config

# Ensure ros user can access ROS setup.bash by giving proper permissions
RUN sudo chmod +rx /opt/ros/jazzy/setup.bash

# Setup sudo: gives the user specified by USERNAME the sudo permissions
RUN apt-get update \
  && apt-get install -y \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  libi2c-dev \
  python3-colcon-common-extensions \
  ros-${ROS_DISTRO}-hardware-interface \
  ros-${ROS_DISTRO}-hardware-interface-testing \
  ros-${ROS_DISTRO}-controller-manager \
  ros-${ROS_DISTRO}-velocity-controllers \
  ros-${ROS_DISTRO}-joint-state-broadcaster \
  ros-${ROS_DISTRO}-robot-state-publisher \
  ros-${ROS_DISTRO}-joint-state-publisher-gui \
  ros-${ROS_DISTRO}-xacro \
  ros-${ROS_DISTRO}-tf2 \
  ros-${ROS_DISTRO}-tf2-msgs \
  ros-${ROS_DISTRO}-rviz2 \
  ros-${ROS_DISTRO}-plotjuggler-ros \
  ros-${ROS_DISTRO}-ros2-control \
  ros-${ROS_DISTRO}-ros2-controllers \
  ros-jazzy-moveit \
  && rm -rf /var/lib/apt/lists/*



RUN apt-get update \
  && apt-get install -y \
  curl \
  lsb-release \
  gnupg \
  && rm -rf /var/lib/apt/lists/*


RUN curl -fsSL https://packages.osrfoundation.org/gazebo.gpg -o /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" > /etc/apt/sources.list.d/gazebo-stable.list \
  && apt-get update \
  && apt-get install -y gz-harmonic \
  ros-${ROS_DISTRO}-ros-gz \
  ros-${ROS_DISTRO}-gz-ros2-control \
  && rm -rf /var/lib/apt/lists/*


USER $USERNAME
WORKDIR /home/$USERNAME

RUN mkdir -p ~/ros2_ws/src

WORKDIR /home/$USERNAME/ros2_ws/src

COPY entrypoint.sh /entrypoint.sh
COPY bashrc /home/$USERNAME/.bashrc

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]

CMD ["bash"]

USER root
