FROM osrf/ros:foxy-desktop-full

RUN apt-get update \
  && apt-get install -y \
  nano \
  vim \
  chromium-browser \
  && rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG USERNAME=ros
ARG USER_ID=1001
ARG GROUP_ID=$USER_ID

RUN groupadd --gid $GROUP_ID $USERNAME \
  && useradd -s /bin/bash --uid $USER_ID --gid $GROUP_ID -m $USERNAME \
  && mkdir /home/$USERNAME/.config && chown $USER_ID:$GROUP_ID /home/$USERNAME/.config

# Ensure ros user can access ROS setup.bash by giving proper permissions
RUN sudo chmod +rx /opt/ros/humble/setup.bash

# Setup sudo: gives the user specified by USERNAME the sudo permissions
RUN apt-get update \
  && apt-get install -y \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && rm -rf /var/lib/apt/lists/*

USER $USERNAME
WORKDIR /home/$USERNAME

RUN mkdir -p ~/ros2_ws/src

WORKDIR /home/$USERNAME/ros2_ws/src

COPY entrypoint.sh /entrypoint.sh
COPY bashrc /home/$USERNAME/.bashrc
ADD /slides /home/$USERNAME/slides

RUN npm install decktape
RUN npm install @shd101wyy/mume

ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]

CMD ["bash"]

USER root
